### ISSUE TITLE
Looking for more than External Links

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/set-syllabus#3]
Yura, can you add the following to the Set Syllabus module?

Currently, we have it finding any syllabus that has an external link. If it isn't an external link, though, it is probably in Pages instead. We originally looked in Pages. If the module finds a syllabus in Modules, but it does have an external link, can you have it look for it in Pages?

If it finds it in Pages instead, get the HTML from that Syllabus Page and put it into the Syllabus tool, like we originally did.

Thanks!

**Comment by YuraVasiuk** [comment]
Sure I will do that.  But I will not be at work today.  I will be at work
tomorrow at 1 pm.  Will that work?


Yura Vasiuk

**Comment by zlw11063** [comment]
Yup! Sounds great.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by YuraVasiuk** [comment]
Ok, thanks.

Yura Vasiuk
